spring.application.name=bars
spring.data.mongodb.uri=mongodb://localhost:27017/test_db
security.jwt.secret=VGhpc0lzQVNlY3VyZUFuZEhTZTI1NktleUZvckJhcnNQcm9qZWN0MTIzNDU2Nzg5MA==
security.jwt.expiration-ms=86400000
analysis.python.base-url=http://localhost:8000
cloudinary.url=CLOUDINARY_URL=cloudinary://339523513764897:FFSN01Q9yRs4MikdH3eftg6h3Gw@dwov7o4xt
cloudinary.folder=bank-audit-reports
storage.local-dir=uploads
